name:                influxer
version:             0.1.0.0
github:              "dustin/influxer"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/influxer#readme>

dependencies:
- base >= 4.7 && < 5
- influxdb
- hjsonpointer
- aeson
- bytestring
- net-mqtt
- megaparsec
- containers
- network-uri
- text
- async
- scientific
- time
- lens

library:
  source-dirs: src

executables:
  influxer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - influxer

tests:
  influxer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - influxer
    - QuickCheck
    - tasty
    - tasty-hunit
    - tasty-quickcheck
